### Create a New Team for the Event
POST http://localhost:5002/api/teams
Content-Type: application/json

{
    "name": "CodeBlasters",
    "eventId": "6a38d128cad36f2d08bb6e9a",
    "leaderId": "64a2b1234567890abcdef123"
}

### Invite a Member to the Team
POST http://localhost:5002/api/teams/6a391d53fb379c02e9547c30/invite
Content-Type: application/json

{
    "userId": "64b3c9876543210fedcba321" 
}


### Accept Team Invitation
PUT http://localhost:5002/api/teams/6a391d53fb379c02e9547c30/accept
Content-Type: application/json

{
    "userId": "64b3c9876543210fedcba321"
}